install.packages("ggplot2")
install.packages("readr")
install.packages("tidycensus")
install.packages("zipcodeR")
install.packages("arm")
install.packages("lme4")
install.packages("ggthemes")
install.packages("tigris")

library("ggplot2")
library("readr")
library("tidycensus")
library("zipcodeR")
library("arm")
library("lme4")
library("ggthemes")
library("tigris")
